constants:
  # Menu
  Menu_Food: "Еда"
  Menu_Food_Journal: "Журнал приема пищи"
  Menu_Food_FoodList: "Управление едой"
  Menu_Food_Stats: "Статистика"
  Menu_Weight: "Вес"
  Menu_Weight_WeightList: "Вес тела"
  Menu_Weight_Stats: "Статистика"
  Menu_Activity: "Активность"
  Menu_Activity_Journal: "Журнал активности"
  Menu_Activity_SportList: "Управление спортом"
  Menu_Activity_Stats: "Статистика"
  Menu_Finance: "Финансы"
  Menu_Finance_BondCalc: "Расчет доходности облигаций"
  Menu_Settings: "Настройки"
  Menu_Settings_CalcCal: "Расчет лимита ккал."
  Menu_Settings_User: "Пользователь"
  # Pages
  Page_Main: "Главная страница"
  Page_NotFound: "Страница не найдена"
  Page_Food_FoodList: "Управление едой"
  Page_Food_FoodEdit: "Редактирование еды"
  Page_Food_FoodCreate: "Создание еды"
  Page_Weight_WeightList: "Вес тела"
  Page_Settings_CalcCal: "Расчет лимита ккал."
  Page_Finance_BondCalc: "Расчет доходности облигаций"
  # Settings
  Settings_Gender: "Пол"
  Settings_GenderM: "Мужской"
  Settings_GenderF: "Женский"
  Settings_Weight: "Вес, кг."
  Settings_Height: "Рост, см."
  Settings_Age: "Возраст, лет"
  Settings_Ubm: "Уровень базального метаболизма, ккал."
  Settings_Activity1: "Сидячая активность"
  Settings_Activity2: "Легкая активность"
  Settings_Activity3: "Средняя активность"
  Settings_Activity4: "Полноценная активность"
  Settings_Activity5: "Cупер активность"
  # Finance
  Finance_Nominal: "Номинал, руб."
  Finance_BondCurrentPrice: "Текущая цена, руб."
  Finance_BondMaturityDate: "Дата погашения облигации"
  Finance_BondNcd: "НКД, руб."
  Finance_BondCd: "КД, руб."
  Finance_BondCdCount: "Количество выплат КД"
  Finance_BondSum: "Сумма приобретения, руб."
  Finance_TotalBoughtCnt: "Количество купленных облигаций"
  Finance_TotalBoughtSum: "Сумма купленных облигаций, руб."
  Finance_DaysToMaturity: "Дней до погашения"
  Finance_YTM: "Доходность к погашению, %г."
  Finance_TotalSum: "Итоговая сумма, руб."
  Finance_DiffSum: "Разница, руб."
  # Food
  Food_Name: "Наименование"
  Food_Brand: "Бренд"
  Food_Cal100: "ККал, 100г."
  Food_Prot100: "Белки, 100г."
  Food_Fat100: "Жиры, 100г."
  Food_Carb100: "Углеводы, 100г."
  Food_CPFC: "КБЖУ, 100г."
  Food_C: "К"
  Food_P: "Б"
  Food_F: "Ж"
  Food_Cb: "У"
  Food_NotFound: "Еда не найдена"
  Food_Saved: "Еда успешно сохранена"
  Food_DeletePrompt: "Удалить еду?"
  # Weight
  Weight_Value: "Вес, кг."
  # Common
  Common_Calc: "Рассчитать"
  Common_ValueG0: "Значение должно быть больше нуля"
  Common_DateGToday: "Дата должна быть больше сегодняшнего дня"
  Common_Search: "Поиск"
  Common_Comment: "Комментарий"
  Common_Date: "Дата"